add new ml4w scripts

diff --git a/dotfiles/.config/ml4w/scripts/ml4w-nvidia b/dotfiles/.config/ml4w/scripts/ml4w-nvidia
--- a/dotfiles/.config/ml4w/scripts/ml4w-nvidia
+++ b/dotfiles/.config/ml4w/scripts/ml4w-nvidia
@@ -3,21 +3,24 @@
 info() { echo -e "${BLUE}[BOOTSTRAP]${NC} $1"; }
 success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
 warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
-error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
+error() {
+    echo -e "${RED}[ERROR]${NC} $1"
+    exit 1
+}
 
 # --- 2. OS DETECTION (By Package Manager) ---
 
-if command -v pacman &> /dev/null; then
+if command -v pacman &>/dev/null; then
     DISTRO="Arch Linux"
     INSTALL_CMD="sudo pacman -S --noconfirm nvidia-open-dkms nvidia-utils nvidia-settings egl-wayland lib32-nvidia-utils"
     CHECK_PKG_CMD="pacman -Qi sddm"
-elif command -v dnf &> /dev/null; then
+elif command -v dnf &>/dev/null; then
     DISTRO="Fedora"
     echo "ERROR: $DISTRO is currently not supported. Please install NVIDIA manually."
     exit 1
     # INSTALL_CMD="sudo dnf install -y sddm qt6-qtsvg qt6-qtvirtualkeyboard qt6-qtmultimedia"
     # CHECK_PKG_CMD="rpm -q sddm"
-elif command -v zypper &> /dev/null; then
+elif command -v zypper &>/dev/null; then
     DISTRO="openSUSE Tumbleweed"
     echo "ERROR: $DISTRO is currently not supported. Please install NVIDIA manually."
     exit 1
@@ -30,8 +33,8 @@ fi
 
 echo
 warn "The script will install the NVIDIA graphics drivers on your system."
-if gum confirm "Do you want to proceed?"
+if gum confirm "Do you want to proceed?"; then
     bash -c "$INSTALL_CMD"
-    echo 'source = ~/.config/hypr/conf/environments/nvidia.conf' > $HOME/.config/hypr/conf/environment.conf
+    echo 'source = ~/.config/hypr/conf/environments/nvidia.conf' >$HOME/.config/hypr/conf/environment.conf
     success "Done!"
 fi
